spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: sweav
      validation-timeout: 1500
      connection-timeout: 2000
      minimum-idle: 2
      maximum-pool-size: 2
      max-lifetime: 590000
      idle-timeout: 0
      transaction-isolation: TRANSACTION_READ_COMMITTED
      pool-name: hikari-rw-pool
      leak-detection-threshold: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    type: com.zaxxer.hikari.HikariDataSource
---
spring:
  config:
    activate:
      on-profile: local, dev, prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/sweav?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&connectionCollation=utf8mb4_0900_ai_ci
      password: sweav
